In [49]:
import pandas as pd
import numpy as np

In [50]:
from skimpy import clean_columns

In [51]:
df = pd.read_csv("LakeData.csv", low_memory = False)

In [52]:
df2 = pd.read_csv("Lake physical data.csv", low_memory = False)

In [53]:
df2.rename(columns={'Lake': 'lake_name'}, inplace=True)

In [54]:
clean_df2 = clean_columns(df2)

4 column names have been cleaned

In [55]:
clean_df2.rename(columns={'lake': 'lake_name'}, inplace=True)

In [56]:
clean_df = clean_columns(df)

52 column names have been cleaned

In [57]:
from datetime import datetime
clean_df['date'] = pd.to_datetime(clean_df['date'], format='%m/%d/%Y')
clean_df

,lake_name,site_type,id_#,date,time,pw,w,total_depth_m,secchi_depth,depth_m,...,ss,f,notes,quanta_#,weather_meter_#,fluorometer_#,aquafluor_#,van_dorn_#,unnamed_50,unnamed_51
0,Beaver Dam,Open,21221BEA2,2021-08-09,15:40,S,S,18.5,2.5,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Beaver Dam,Open,18190BEA2,2018-07-09,15:00,S,S,18.0,3.0,0.0,...,NaN,NaN,AQUATIC WEED CONTROL SPRAYED IN THE MORNING (7...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Beaver Dam,Open,18204BEA2,2018-07-23,15:15,R,R,19.0,5.8,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Beaver Dam,Open,18211BEA2,2018-07-31,15:00,O,O,18.6,4.4,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Beaver Dam,Open,18218BEA2,2018-08-06,14:45,S,O,18.8,4.4,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24215,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24216,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24217,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24218,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24219,Beaver Dam,Open,16253BEA2,2016-09-09,13:37,R,O,18.4,4.6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
cdf = clean_df[["lake_name",'date','mc_ppb', 'do_mg_l', 'water_temp_cel_s']]
cdf = cdf.dropna()
cdf.head()

    lake_name       date  mc_ppb  do_mg_l  water_temp_cel_s
1  Beaver Dam 2018-07-09   0.075     8.75             28.83
2  Beaver Dam 2018-07-23   0.075     7.27             25.21
3  Beaver Dam 2018-07-31   0.075     8.55             25.10
4  Beaver Dam 2018-08-06   0.075     9.30             28.77
5  Beaver Dam 2020-06-01   0.075    13.83             22.40

In [59]:
cdf.index = pd.to_datetime(cdf['date'])

In [60]:
cdf = cdf.drop(['date'], axis=1)

In [61]:
cdf

               lake_name  mc_ppb  do_mg_l  water_temp_cel_s
date
2018-07-09    Beaver Dam   0.075     8.75             28.83
2018-07-23    Beaver Dam   0.075     7.27             25.21
2018-07-31    Beaver Dam   0.075     8.55             25.10
2018-08-06    Beaver Dam   0.075     9.30             28.77
2020-06-01    Beaver Dam   0.075    13.83             22.40
...                  ...     ...      ...               ...
2010-08-17        Winona   0.075     7.36             27.00
2010-09-22        Winona   0.075     9.40             21.30
2012-09-10        Winona   0.075     7.61             24.40
2016-07-20        Winona   0.075     9.44             27.58
2012-09-13  Yellow Creek   0.607     7.56             23.60

[1269 rows x 4 columns]

In [62]:
from tslearn.clustering import TimeSeriesKMeans
model = TimeSeriesKMeans(n_clusters=3, metric="dtw", max_iter=10)
model.fit(cdf)
#model.predict(cdf)

ValueError: could not convert string to float: 'Beaver Dam'

In [64]:
cdf.pivot(index="lake_name", columns=["mc_ppb", "do_mg_l"],values="mc_ppb")

ValueError: Index contains duplicate entries, cannot reshape