In [1]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv("LakeData.csv", low_memory = False)
df

,Lake Name,Site type,ID #,Date,Time,PW,W,TotalDepth(m),SecchiDepth,Depth(m),...,SS,F,Notes,Quanta #,Weather Meter #,Fluorometer #,Aquafluor #,Van Dorn #,Unnamed: 50,Unnamed: 51
0,Beaver Dam,Open,21221BEA2,8/9/2021,15:40,S,S,18.5,2.5,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Beaver Dam,Open,18190BEA2,7/9/2018,15:00,S,S,18.0,3.0,0.0,...,NaN,NaN,AQUATIC WEED CONTROL SPRAYED IN THE MORNING (7...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Beaver Dam,Open,18204BEA2,7/23/2018,15:15,R,R,19.0,5.8,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Beaver Dam,Open,18211BEA2,7/31/2018,15:00,O,O,18.6,4.4,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Beaver Dam,Open,18218BEA2,8/6/2018,14:45,S,O,18.8,4.4,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24219,Beaver Dam,Open,16253BEA2,9/9/2016,13:37,R,O,18.4,4.6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
list(df.columns)

['Lake Name',
 'Site type',
 'ID #',
 'Date',
 'Time',
 'PW',
 'W',
 'TotalDepth(m)',
 'SecchiDepth',
 'Depth(m)',
 'Epi/Hypo',
 'WaterTemp(CelS)',
 'DO(% sat)',
 'DO(mg/l)',
 'pH',
 'Con (mS/cm)',
 'MC ID',
 'AC ID',
 'Nutrient ID',
 'Layer',
 'AT (Â°C)',
 'Bar P (mbar)',
 'Alt (m)',
 'Max WS (m/h)',
 'Avg WS (m/h)',
 'Wind Direction',
 'Chloro 1 Fluorosense',
 'Chloro  2 Fluorosense',
 'Phyco 1  Fluorosense',
 'Phyco 2 Fluorosense',
 'MC (ppb)',
 'NH3',
 'Cl',
 'SO4',
 'NO2',
 'NO3',
 'SiO2',
 'SRP',
 'TP',
 'TKN',
 'TN',
 'COND',
 'SS',
 'F',
 'Notes',
 'Quanta #',
 'Weather Meter #',
 'Fluorometer #',
 'Aquafluor #',
 'Van Dorn #',
 'Unnamed: 50',
 'Unnamed: 51']

In [16]:
df = df.dropna(subset=['MC (ppb)'])
df = df.drop(['PW', 'W', 'Epi/Hypo','MC ID', 'AC ID', 'Notes', 'Unnamed: 50', 'Unnamed: 51'], axis=1)
df

,Lake Name,Site type,ID #,Date,Time,TotalDepth(m),SecchiDepth,Depth(m),WaterTemp(CelS),DO(% sat),...,TKN,TN,COND,SS,F,Quanta #,Weather Meter #,Fluorometer #,Aquafluor #,Van Dorn #
1,Beaver Dam,Open,18190BEA2,7/9/2018,15:00,18.0,3.0,0.0,28.83,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Beaver Dam,Open,18204BEA2,7/23/2018,15:15,19.0,5.8,0.0,25.21,88.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Beaver Dam,Open,18211BEA2,7/31/2018,15:00,18.6,4.4,0.0,25.10,103.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Beaver Dam,Open,18218BEA2,8/6/2018,14:45,18.8,4.4,0.0,28.77,120.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Beaver Dam,Open,20153BEA2,6/1/2020,15:00,19.2,1.6,0.0,22.40,160.1,...,NaN,NaN,NaN,NaN,NaN,1,1,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2618,Winona,Open,10229WIN2,8/17/2010,8:45,22.9,3.5,1.0,27.00,92.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2619,Winona,Open,10265WIN2,9/22/2010,16:38,NaN,5.5,1.0,21.30,105.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2620,Winona,Open,12254WIN2,9/10/2012,17:15,NaN,6.9,1.0,24.40,90.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2621,Winona,Open,16202WIN2,7/20/2016,13:50,23.9,3.9,1.0,27.58,118.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2622,Yellow Creek,Open,12257YEL2,9/13/2012,10:15,17.0,6.0,1.0,23.60,88.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN